#this is a comment
CC=clang
OBJ=linked_list
FLAGS=-Wall
all:
	$(CC) $(FLAGS) traversing_ll.c -o $(OBJ)
	chmod +x $(OBJ)
exec:
	./$(OBJ)
clean:
	rm -rf *.out
	rm -rf linked_list
	rm -rf simple_linked_list
	rm -rf sample 
